namespace HudWorkshop;

public sealed record HudElement(string Id, string Label, bool Hotbar = false);
public sealed partial class Plugin
{
    private static readonly HudElement[] Elements =
    [
        new("_ActionBar", "Панель 1", true), new("_ActionBar01", "Панель 2", true),
        new("_ActionBar02", "Панель 3", true), new("_ActionBar03", "Панель 4", true),
        new("_ActionBar04", "Панель 5", true), new("_ActionBar05", "Панель 6", true),
        new("_ActionBar06", "Панель 7", true), new("_ActionBar07", "Панель 8", true),
        new("_ActionBar08", "Панель 9", true), new("_ActionBar09", "Панель 10", true),
        new("ChatLog", "Чат"),
        new("ChatLogPanel_0", "Чат — вкладка 1"), new("ChatLogPanel_1", "Чат — вкладка 2"),
        new("ChatLogPanel_2", "Чат — вкладка 3"), new("ChatLogPanel_3", "Чат — вкладка 4"),
        new("_ParameterWidget", "Параметры персонажа — HP/MP"), new("_Exp", "Опыт"),
        new("_NaviMap", "Миникарта"), new("_ToDoList", "Список заданий"),
        new("ScenarioTree", "Основной сюжет"), new("_DTR", "Информация о сервере"),
        new("_Money", "Гил"), new("_BagWidget", "Занятость инвентаря"),
        new("_MainCommand", "Главное меню"), new("_Notification", "Уведомления"),
        new("_CastBar", "Полоса применения способности"), new("_TargetInfo", "Цель — общая панель"),
        new("_TargetInfoMainTarget", "Цель — имя и HP"), new("_TargetInfoCastBar", "Цель — применение способности"),
        new("_TargetInfoBuffDebuff", "Цель — эффекты"), new("_FocusTargetInfo", "Цель в фокусе"),
        new("_PartyList", "Список группы"), new("_AllianceList1", "Альянс 1"),
        new("_AllianceList2", "Альянс 2"), new("_EnemyList", "Список противников"),
        new("_Status", "Статус-эффекты — общая панель"),
        new("_StatusCustom0", "Статус-эффекты — усиления"),
        new("_StatusCustom1", "Статус-эффекты — ослабления"),
        new("_StatusCustom2", "Статус-эффекты — прочие"),
        new("_StatusCustom3", "Статус-эффекты — условные усиления"),
        new("_LimitBreak", "Предельная способность"), new("_ContentGauge", "Шкала миссии"),
        new("_ActionContents", "Действие миссии"),
        new("JobHudPLD0", "Паладин — шкала клятвы"),
        new("JobHudMNK1", "Монах — шкала 1"),
        new("JobHudMNK0", "Монах — шкала 0"),
        new("JobHudWAR0", "Воин — шкала 0"),
        new("JobHudDRG0", "Драгун — шкала 0"),
        new("JobHudBRD0", "Бард — шкала 0"),
        new("JobHudWHM0", "Белый маг — шкала 0"),
        new("JobHudBLM0", "Чёрный маг — шкала 0"),
        new("JobHudBLM1", "Чёрный маг — шкала 1"),
        new("JobHudACN0", "Арканист — шкала 0"),
        new("JobHudSMN1", "Призыватель — шкала 1"),
        new("JobHudSMN0", "Призыватель — шкала 0"),
        new("JobHudSCH0", "Учёный — шкала 0"),
        new("JobHudNIN1v70", "Ниндзя — шкала 1v70"),
        new("JobHudNIN0", "Ниндзя — шкала 0"),
        new("JobHudMCH0", "Машинист — шкала 0"),
        new("JobHudDRK0", "Тёмный рыцарь — шкала 0"),
        new("JobHudDRK1", "Тёмный рыцарь — шкала 1"),
        new("JobHudAST0", "Астролог — шкала 0"),
        new("JobHudSAM1", "Самурай — шкала 1"),
        new("JobHudSAM0", "Самурай — шкала 0"),
        new("JobHudRDM0", "Красный маг — шкала 0"),
        new("JobHudGNB0", "Ганбрейкер — шкала 0"),
        new("JobHudDNC0", "Танцор — шкала 0"),
        new("JobHudDNC1", "Танцор — шкала 1"),
        new("JobHudRRP0", "Жнец — шкала 0"),
        new("JobHudRRP1", "Жнец — шкала 1"),
        new("JobHudGFF0", "Мудрец — шкала 0"),
        new("JobHudGFF1", "Мудрец — шкала 1"),
        new("JobHudRDB0", "Вайпер — шкала 0"),
        new("JobHudRDB1", "Вайпер — шкала 1"),
        new("JobHudRPM0", "Пиктомант — шкала 0"),
        new("JobHudRPM1", "Пиктомант — шкала 1"),
        new("JobHudXBM0", "Дополнительная шкала профессии 1"),
        new("JobHudXBM1", "Дополнительная шкала профессии 2"),
        new("_ActionBarEx", "Дополнительная панель команд"),
        new("PvPColosseumHeader", "PvP — счёт арены"),
        new("PvPColosseumPartyList0", "PvP — группа 1"),
        new("PvPColosseumPartyList1", "PvP — группа 2"),
        new("PvPMKSBattleLog", "PvP — журнал боя"),
        new("PvPMKSHeader", "PvP — состояние матча"),
        new("PvPMKSPartyList1", "PvP — список команды 1"),
        new("PvPMKSPartyList3", "PvP — список команды 2"),
        new("PvPMap", "PvP — карта"),
        new("PvPFrontlineHeader", "Фронт — счёт"),
        new("PvPFrontlineGauge", "Фронт — шкала"),
        new("PvPFrontlineInfo", "Фронт — информация"),
        new("ManeuversHeader", "Соперничество крыльев — счёт"),
        new("ManeuversAllianceList", "Соперничество крыльев — альянс"),
        new("ManeuversTeamInfo", "Соперничество крыльев — команда"),
        new("ManeuversStation", "Соперничество крыльев — станция"),
        new("ManeuversGoblinSoldier", "Соперничество крыльев — наёмники"),
        new("HWDAetherGauge", "Реставрация — эфир"),
        new("QuestRedoHud", "Новая игра+"),
        new("IKDMission", "Морская рыбалка — задания"),
        new("FGSHudGoal", "Золотое блюдце — цель"),
        new("FGSHudScore", "Золотое блюдце — счёт"),
        new("FGSHudStatus", "Золотое блюдце — статус"),
        new("FGSHudRaceLog", "Золотое блюдце — журнал"),
        new("WKSAnnounce", "Космическое исследование — уведомления"),
    ];
    private static bool IsChat(string id) => id == "ChatLog" || id.StartsWith("ChatLogPanel_",StringComparison.Ordinal);
    private static readonly HashSet<uint> ChatHashes=Elements.Where(e=>IsChat(e.Id)).Select(e=>Crc32(e.Id+"_a")).ToHashSet();
    private static readonly string[] Names = Elements.Select(e => e.Id).ToArray();
    private static HashSet<string>? registeredHudNames;
}
